# Gradle Properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 -Dtrust_all_cert=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=false

# Compose
kotlin.code.style=official

# Suppress SDK compatibility warning
android.suppressUnsupportedCompileSdk=37

# 禁用 App Bundle，只生成 APK
android.defaults.buildfeatures.buildconfig=true
android.enableBundle=false
