# Gradle Properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 -Dtrust_all_cert=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=false

# Compose
kotlin.code.style=official
